'use strict';
/* 戰國風雲：關鍵人物卡資料
 * 每位人物：name 名稱／kana 日文讀音（假名）／romaji 羅馬字／years 生卒年／clan 家系／mon 家紋
 * portrait 肖像（Wikimedia Commons，已逐檔確認授權）／bio 簡介／roles 各幕角色（以年份為鍵）
 * routes 各幕地圖上要強調的路線或衝突範圍（r＝路線、z＝範圍，對應 routes-data.js 的順序）
 * quote 名言：status 'attested'＝見於同時代或本人史料；'attributed'＝傳為某人所說，有疑義
 * myths 常見但屬後世創作或可疑的說法（卡片上以「傳說」標示）
 */
(function () {
const C = 'https://commons.wikimedia.org/wiki/File:';
const K = 'https://kotobank.jp/word/';
const mon = (name, file, title, author, license) => ({ name, file: 'img/mon/' + file, page: C + title.replace(/ /g, '_'), title, author, license });
const pic = (id, title, author, holder, license, date, note) => ({ file: 'img/figures/' + id + '.webp', page: C + title.replace(/ /g, '_'), title, author, holder, license, date, note });
const koto = (n, id) => ({ t: 'コトバンク｜' + n, u: K + encodeURIComponent(n) + '-' + id });

const MON = {
  ashikaga: mon('足利二つ引（丸に二つ引）', 'ashikaga.png', 'Japanese Crest Marunouti ni Futatu Hiki.svg', 'Mukai', 'CC BY-SA 3.0'),
  hosokawa: mon('細川九曜', 'hosokawa.png', 'Japanese Crest Hosokawa Kuyou.svg', 'Mukai', 'CC BY-SA 3.0'),
  yamana: mon('五七桐に七葉根笹', 'yamana.png', '五七桐に七葉根笹.png', 'Houunji 1642', 'CC BY-SA 3.0'),
  togashi: mon('八曜', 'togashi.png', 'Hachiyou.svg', 'Gameposo', 'CC BY-SA 4.0'),
  honganji: mon('下り藤（本願寺寺紋）', 'honganji.png', 'Japanese crest Sagari Fuji.svg', 'Mukai', 'CC BY-SA 3.0'),
  tanegashima: mon('三つ鱗', 'tanegashima.png', 'Japanese Crest mitu Uroko.svg', 'Mukai', 'CC BY-SA 3.0'),
  oda: mon('織田木瓜', 'oda.png', 'Japanese Crest Oda ka.svg', 'Mukai', 'CC BY-SA 3.0'),
  imagawa: mon('赤鳥', 'imagawa.png', 'Imagawa Akadori (No background and Black color drawing).svg', 'Gameposo（Marnanel 向量化）', 'CC BY-SA 4.0'),
  tokugawa: mon('三つ葉葵', 'tokugawa.png', 'Japanese crest Tokugawa Aoi.svg', 'Mukai', 'CC BY-SA 3.0'),
  rokkaku: mon('隅立て四つ目結', 'rokkaku.png', 'Sumitateyotsumeyui（２）.png', '赤口利之助三郎', 'CC0'),
  azai: mon('三つ盛亀甲に花菱', 'azai.png', 'Japanese Crest mitumori Kikkou ni Hanabishi.svg', 'Wikiwikiyarou', 'CC BY-SA 3.0'),
  asakura: mon('三つ盛木瓜', 'asakura.png', 'Japanese Crest mitumori mokkou.svg', 'Mukai', 'CC BY-SA 3.0'),
  takeda: mon('武田菱', 'takeda.png', 'Japanese Crest Takeda Hisi.svg', 'Mukai', 'CC BY-SA 3.0'),
  akechi: mon('桔梗（土岐桔梗）', 'akechi.png', 'Tokikikyo.svg', 'Lemon-s（推定）', '公有領域'),
  toyotomi: mon('五七桐（太閤桐）', 'toyotomi.png', 'Taiko Giri.svg', 'WTCA', '公有領域'),
  shibata: mon('二つ雁金', 'shibata.png', 'Japanese Crest futatu Karigane.svg', 'Mukai', 'CC BY-SA 3.0'),
  maeda: mon('加賀梅鉢', 'maeda.png', 'Japanese crest Kaga Umebachi.svg', 'Mukai', 'CC BY-SA 3.0'),
  hojo: mon('北條鱗（三つ鱗）', 'hojo.png', 'Japanese Crest Houjou Uroko.svg', 'Mukai', 'CC BY-SA 3.0'),
  kato: mon('蛇の目', 'kato.png', 'Japanese Crest janome.svg', 'Los688（向量化）', '公有領域'),
  ishida: mon('大一大萬大吉', 'ishida.png', 'Japanese Crest Daiichi Daiman Daikichi.svg', 'Gameposo（Marnanel 向量化）', 'CC BY-SA 3.0'),
  mori: mon('一文字三星', 'mori.png', 'Ichimonjimitsuboshi.png', 'Kashiwamon', 'CC BY-SA 4.0'),
  kobayakawa: mon('左三つ巴', 'kobayakawa.png', 'Hidari mitsudomoe.svg', 'BraneJ', 'CC BY-SA 3.0'),
  sanada: mon('六文錢', 'sanada.png', 'Japanese Crest rokumonsen.svg', 'Los688（向量化）', '公有領域')
};

const MYTH_HOTOTOGISU = { text: '杜鵑三句（「鳴かぬなら殺してしまえ／鳴かせてみせよう／鳴くまで待とう」）', note: '見於江戶後期松浦靜山《甲子夜話》所錄的後人之作，用來比喻三人性格，並非信長、秀吉、家康本人所說。' };

const F = [
{ id: 'ashikaga-yoshimasa', name: '足利義政', kana: 'あしかが よしまさ', romaji: 'Ashikaga Yoshimasa', years: '1436–1490',
  clan: '足利氏（室町幕府第八代將軍）', mon: MON.ashikaga,
  portrait: pic('ashikaga-yoshimasa', 'Ashikaga Yoshimasa.jpg', '傳土佐光信', null, '公有領域', '15 世紀後半', '畫像傳為義政像'),
  bio: '室町幕府第八代將軍。將軍繼承（弟義視與親子義尚）之爭與管領家的家督糾紛交纏，成為應仁之亂的背景；晚年營建東山山莊（今銀閣寺），東山文化因而得名。',
  roles: { 1467: '在位將軍。繼承人之爭是東西兩軍對立的導火線之一，但他無力讓雙方停戰。' },
  routes: { 1467: ['z0'] },
  sources: [koto('足利義政', 14305)] },
{ id: 'hosokawa-katsumoto', name: '細川勝元', kana: 'ほそかわ かつもと', romaji: 'Hosokawa Katsumoto', years: '1430–1473',
  clan: '細川京兆家（管領）', mon: MON.hosokawa,
  portrait: pic('hosokawa-katsumoto', 'Hosokawa Katsumoto.jpg', '作者不詳', '圖像出自讀賣新聞社《妙心寺》圖錄（2009）', '公有領域', '17 世紀', null),
  bio: '室町幕府管領，應仁之亂東軍的總帥，與西軍的山名宗全（勝元的岳父）爭奪幕政主導權。戰事未了，1473 年病逝；京都龍安寺由他創建。',
  roles: { 1467: '東軍主將，以將軍御所一帶為據點，與西軍在京都市街對峙。' },
  routes: { 1467: ['z0'] },
  sources: [koto('細川勝元', 14966)] },
{ id: 'yamana-sozen', name: '山名宗全', alias: ['山名持豐'], kana: 'やまな そうぜん', romaji: 'Yamana Sōzen', years: '1404–1473',
  clan: '山名氏（本名持豐，宗全為法號）', mon: MON.yamana,
  portrait: pic('yamana-sozen', 'Dai Nihon Rokujūyoshō, Bingo Yamana Uemonnokami Mochitoyo Nyūdō Sōzen by Yoshitora.jpg', '歌川芳虎', null, '公有領域', '約 1866 年', '幕末浮世繪，屬後世想像畫像'),
  bio: '嘉吉之亂後擴張勢力、兼任多國守護的大名，應仁之亂西軍的總帥。西軍本陣在堀川以西，京都「西陣」的地名即由此而來。1473 年與勝元同年病逝。',
  roles: { 1467: '西軍主將。周防的大內政弘率軍上洛加入西軍，使戰局拉長。' },
  routes: { 1467: ['z0', 'r0'] },
  sources: [koto('山名宗全', 144255)] },
{ id: 'togashi-masachika', name: '富樫政親', kana: 'とがし まさちか', romaji: 'Togashi Masachika', years: '1455–1488',
  clan: '富樫氏（加賀守護）', mon: MON.togashi, portrait: null, portraitNote: '未找到可信且屬公有領域的肖像。',
  bio: '加賀守護。1474 年曾借本願寺門徒之力擊敗弟弟幸千代，之後卻與門徒對立、加以鎮壓。1488 年遭門徒與國人組成的一揆包圍於高尾城，自盡。',
  roles: { 1488: '被一揆勢包圍在高尾城的守護，城破前自盡。' },
  routes: { 1488: ['z0'] },
  sources: [koto('富樫政親', 104547), koto('加賀一向一揆', 824247)] },
{ id: 'honganji-monto', group: true, name: '本願寺門徒', kana: 'ほんがんじ もんと', romaji: 'Honganji montō', years: '15–16 世紀',
  clan: '淨土真宗本願寺派的信徒集團', mon: MON.honganji, monNote: '下り藤為本願寺的寺紋，並非門徒各家的家紋。', portrait: null,
  bio: '蓮如在北陸傳教（1471 年起據吉崎御坊）後，加賀門徒以「講」「組」結合，並與國人（在地武士）合流。1488 年推翻守護富樫政親，此後近百年加賀由門徒與本願寺勢力主導，直到 1580 年金澤御堂被柴田勝家攻陷。',
  roles: { 1488: '一揆的主力之一，與國人共同包圍高尾城，推翻守護。' },
  routes: { 1488: ['z0'] },
  quote: { text: '百姓ノ持タル國ノヤウニナリ行キ候', zh: '（加賀）漸漸變得像是百姓所擁有的國家', source: '《實悟記拾遺》（本願寺僧實悟的追述，成書於事件數十年後）', status: 'attested',
    note: '「百姓之國」是當時人的形容，不代表一般農民真的平等統治了一百年。' },
  sources: [koto('加賀一向一揆', 824247)] },
{ id: 'tanegashima-tokitaka', name: '種子島時堯', kana: 'たねがしま ときたか', romaji: 'Tanegashima Tokitaka', years: '1528–1579',
  clan: '種子島氏（種子島島主）', mon: MON.tanegashima, portrait: null, portraitNote: 'Commons 上只有墓所照片，沒有肖像。',
  bio: '種子島的領主。據《鐵炮記》，他向漂抵島上的葡萄牙人購買兩挺火繩槍，命家臣學習射擊與火藥調配，並讓工匠仿製，火繩槍由此傳入日本。',
  roles: { 1543: '向葡萄牙人購得火繩槍，命家臣學射擊、工匠仿製。' },
  routes: { 1543: ['r0', 'r1'] },
  myths: [{ text: '「1543 年」是確定的傳入年份', note: '1543 年依據的是 1606 年成書的《鐵炮記》；葡萄牙方面的加爾旺（António Galvão）記為 1542 年。' }],
  sources: [koto('種子島時尭', 562047), koto('鉄炮記', 101145)] },
{ id: 'portuguese', group: true, foreign: true, name: '葡萄牙商人', kana: 'ポルトガル商人', romaji: 'Portuguese merchants', years: '1540 年代',
  clan: '搭乘中國帆船而來的葡萄牙人', mon: null, monNote: '歐洲商人沒有日本式家紋。', portrait: null,
  bio: '《鐵炮記》說他們搭乘一艘中國船漂抵種子島，記其名為「牟良叔舍」「喜利志多佗孟太」，船上的「大明儒生五峰」通說即倭寇首領王直。葡萄牙方面加爾旺的記載則列出 António da Mota、Francisco Zeimoto、António Peixoto 三人。',
  roles: { 1543: '乘中國船抵達種子島，帶來火繩槍，成為日本與歐洲接觸的開端之一。' },
  routes: { 1543: ['r0'] },
  myths: [{ text: '平托（Fernão Mendes Pinto）自稱是第一批抵日的葡萄牙人', note: '出自其遊記《遠遊記》，內容多有誇張，一般不採信。' }],
  sources: [koto('鉄炮記', 101145)] },
{ id: 'gunsmiths', group: true, name: '鐵匠', kana: 'てっぽうかじ', romaji: 'teppō kaji', years: '16 世紀',
  clan: '刀工與鐵砲鍛冶', mon: null, monNote: '泛指工匠群體，沒有家紋。', portrait: null,
  bio: '種子島的刀工奉命仿製火繩槍，最大的難題是封住槍管後端的螺絲（尾栓）。此後堺、紀伊根來、近江國友等地成為主要產地，火器透過商人與工匠網絡在數十年間傳遍各地。',
  roles: { 1543: '仿製火繩槍，把技術傳往堺、根來、國友等地。' },
  routes: { 1543: ['r1'] },
  myths: [{ text: '刀工八板金兵衛把女兒若狹嫁給葡萄牙人，換取尾栓螺絲的製法', note: '是後世流傳的地方傳說，同時代史料沒有記載。' }],
  sources: [koto('八板金兵衛', 1116142)] },
{ id: 'oda-nobunaga', name: '織田信長', kana: 'おだ のぶなが', romaji: 'Oda Nobunaga', years: '1534–1582',
  clan: '織田氏（尾張）', mon: MON.oda,
  portrait: pic('oda-nobunaga', 'Oda-Nobunaga.jpg', '狩野宗秀', '圖像出處：東京大學史料編纂所', '公有領域', '1583 年', null),
  bio: '尾張大名。在桶狹間擊敗今川義元後，平定美濃、擁立足利義昭進入京都，逐步成為畿內最強的軍事力量。1582 年在京都本能寺遭明智光秀襲擊身亡。',
  roles: {
    1560: '從清洲出兵，在桶狹間攻擊今川本隊，義元戰死。',
    1568: '擁立足利義昭，經近江率軍進入京都。',
    1573: '與義昭決裂，逼其離開京都；同年消滅朝倉、淺井。',
    1575: '率主力救援長篠，與德川軍在設樂原擊敗武田勝賴。',
    1582: '停留本能寺時遭明智光秀襲擊，自盡。'
  },
  routes: { 1560: ['r1'], 1568: ['r1'], 1573: ['r2'], 1575: ['r1'], 1582: ['r0'] },
  quote: { text: '是非に及ばず', zh: '事已至此，無可奈何（也可解作「不必多說」）', source: '太田牛一《信長公記》卷十五，得知襲擊者是明智軍時所說', status: 'attested',
    note: '作者並不在現場，而是根據倖存侍女的轉述記錄。' },
  myths: [
    { text: '「人間五十年，下天のうちをくらぶれば……」是信長的名言', note: '其實是幸若舞《敦盛》的詞句，並非信長所作；《信長公記》只記載他在桶狹間出陣前唱舞這一段。' },
    MYTH_HOTOTOGISU
  ],
  sources: [koto('織田信長', 17785), koto('敦盛', 425663), koto('甲子夜話', 45237)] },
{ id: 'imagawa-yoshimoto', name: '今川義元', kana: 'いまがわ よしもと', romaji: 'Imagawa Yoshimoto', years: '1519–1560',
  clan: '今川氏（駿河、遠江、三河）', mon: MON.imagawa,
  portrait: pic('imagawa-yoshimoto', 'ImagawaYoshimoto.jpg', '作者不詳', '收藏處未標示', '公有領域', null, 'Commons 檔案取自網路部落格，原件收藏處未標示'),
  bio: '統治駿河、遠江、三河的大名，增訂分國法《今川假名目錄》，並與武田、北條締結三國同盟。1560 年率大軍進入尾張，在桶狹間遭信長攻擊而戰死。',
  roles: { 1560: '率今川軍進入尾張，在桶狹間遭織田軍攻擊本隊，戰死。' },
  routes: { 1560: ['r0'] },
  myths: [{ text: '義元出兵是為了「上洛」奪取天下，且是個塗黑齒的柔弱貴族', note: '「上洛說」目前多受質疑，較多研究者認為目的是確保尾張邊境；柔弱形象主要來自後世的小說與戲劇。' }],
  sources: [koto('今川義元', 32217)] },
{ id: 'tokugawa-ieyasu', name: '德川家康', alias: ['松平元康'], kana: 'とくがわ いえやす', romaji: 'Tokugawa Ieyasu', years: '1543–1616',
  clan: '松平氏→德川氏（三河出身）', mon: MON.tokugawa,
  portrait: pic('tokugawa-ieyasu', 'Tokugawa Ieyasu2 full.JPG', '狩野探幽', null, '公有領域', '17 世紀', null),
  bio: '三河松平氏出身，幼年曾在今川家當人質。桶狹間之戰後自立，與信長結盟；秀吉死後在關原之戰獲勝，1603 年就任征夷大將軍，1615 年大坂夏之陣消滅豐臣氏。',
  roles: {
    1560: '當時名為松平元康，屬今川方，負責向大高城運糧；義元戰死後回到岡崎，逐步自立。',
    1575: '長篠城屬德川方，他與信長聯軍前往救援，擊敗武田軍。',
    1582: '本能寺之變時人在堺，經伊賀山路逃回三河（伊賀越）。',
    1590: '參與小田原征伐，戰後轉封關東，以江戶為據點。',
    1600: '率東軍主力西進，在關原擊敗西軍。',
    1603: '受封征夷大將軍，開設江戶幕府。',
    1615: '以大御所身分指揮大坂夏之陣，豐臣氏滅亡。'
  },
  routes: { 1560: ['r0'], 1575: ['r2'], 1582: ['r2'], 1590: ['r2'], 1600: ['r0'], 1603: ['r0'], 1615: ['r0', 'r2'] },
  myths: [
    { text: '「人の一生は重荷を負うて遠き道を行くが如し」（東照公遺訓）', note: '一般認為是後世託名之作，並非家康親筆。' },
    MYTH_HOTOTOGISU
  ],
  sources: [koto('徳川家康', 19082), { t: '日本國立公文書館｜德川家康年表', u: 'https://www.archives.go.jp/exhibition/digital/ieyasu/history.html' }] },
{ id: 'ashikaga-yoshiaki', name: '足利義昭', kana: 'あしかが よしあき', romaji: 'Ashikaga Yoshiaki', years: '1537–1597',
  clan: '足利氏（室町幕府第十五代將軍）', mon: MON.ashikaga,
  portrait: pic('ashikaga-yoshiaki', 'Ashikaga Yoshiaki.jpg', '作者不詳', '翻拍自 1941 年《國史肖像集成》（目黑書店）', '公有領域', null, '照片中為木像'),
  bio: '室町幕府最後一位將軍。兄長義輝被殺後，他從奈良出逃，先投靠越前朝倉氏，後依靠信長上洛就任將軍。後來與信長失和，1573 年被逐出京都，之後在毛利氏庇護下仍保有將軍名號多年。',
  roles: {
    1568: '從越前轉往美濃投靠信長，在信長擁立下入京，就任第十五代將軍。',
    1573: '舉兵反抗信長，在槇島城投降後離開京都，前往河內。'
  },
  routes: { 1568: ['r0'], 1573: ['r3'] },
  myths: [{ text: '1573 年室町幕府正式「滅亡」', note: '義昭離京後仍保有將軍職，到 1588 年才辭官；「1573 年滅亡」是以政權在京都瓦解為準的通行劃分。' }],
  sources: [koto('足利義昭', 14542)] },
{ id: 'rokkaku-jotei', name: '六角承禎', alias: ['六角義賢'], kana: 'ろっかく じょうてい', romaji: 'Rokkaku Jōtei (Yoshikata)', years: '1521–1598',
  clan: '六角氏（南近江守護）；承禎為出家後的法號，本名義賢', mon: MON.rokkaku,
  portrait: pic('rokkaku-jotei', 'Rokkaku Shōtei.jpg', '歌川芳幾', null, '公有領域', '1867 年', '幕末浮世繪，屬後世想像畫像'),
  bio: '南近江守護六角氏的首領（當時家督已傳給兒子義治，實權仍在他手中）。1568 年拒絕協助義昭與信長上洛，觀音寺城一帶被攻破後退往甲賀，此後長期以游擊方式對抗織田。',
  roles: { 1568: '以觀音寺城阻擋上洛軍；箕作城陷落後棄城，退往甲賀。' },
  routes: { 1568: ['r1'] },
  sources: [koto('六角義賢', 153006)] },
{ id: 'azai-nagamasa', name: '淺井長政', kana: 'あざい ながまさ', romaji: 'Azai Nagamasa', years: '1545–1573',
  clan: '淺井氏（北近江）', mon: MON.azai,
  portrait: pic('azai-nagamasa', 'Azai-Nagamasa-cropped.jpg', '作者不詳', '高野山持明院', '公有領域', '17 世紀', null),
  bio: '北近江的大名，娶信長之妹阿市。1570 年信長攻打朝倉時倒戈，同年在姊川之戰落敗；1573 年小谷城陷落，自盡。三個女兒茶茶（淀殿）、初、江日後分別牽動豐臣、京極與德川家。',
  roles: { 1573: '與朝倉聯手抗信長，小谷城被攻陷後自盡。' },
  routes: {}, routeNote: '本幕地圖未畫出淺井軍的行軍路線。',
  myths: [{ text: '阿市送來兩端紮緊的紅豆袋，暗示信長被前後包夾', note: '是江戶時代軍記物中的情節，同時代史料沒有記載。' }],
  sources: [koto('浅井長政', 24965)] },
{ id: 'asakura-yoshikage', name: '朝倉義景', kana: 'あさくら よしかげ', romaji: 'Asakura Yoshikage', years: '1533–1573',
  clan: '朝倉氏（越前）', mon: MON.asakura,
  portrait: pic('asakura-yoshikage', 'Asakura Yoshikage2.jpg', '作者不詳', '收藏處未標示', '公有領域', null, 'Commons 未標示原件收藏處'),
  bio: '越前的大名，本據地一乘谷是當時繁華的城下町。曾收留足利義昭，但沒有擁他上洛。1573 年出兵救援小谷城失敗，撤退時在刀根坂大敗，最後遭一族的朝倉景鏡背叛而自盡。',
  roles: { 1573: '出兵救援淺井失敗，撤退途中潰敗，逃回越前後自盡，朝倉氏滅亡。' },
  routes: {}, routeNote: '本幕地圖未畫出朝倉軍的行軍路線。',
  sources: [koto('朝倉義景', 25012)] },
{ id: 'takeda-katsuyori', name: '武田勝賴', kana: 'たけだ かつより', romaji: 'Takeda Katsuyori', years: '1546–1582',
  clan: '武田氏（甲斐）', mon: MON.takeda,
  portrait: pic('takeda-katsuyori', 'Takeda Katsuyori.jpg', '作者不詳', '高野山持明院', '公有領域', '16 世紀後半', null),
  bio: '武田信玄的四子，信玄死後繼承武田家。1574 年攻下高天神城，勢力一度擴大；1575 年長篠之戰大敗後仍維持政權。1582 年織田、德川軍攻入甲斐，他在天目山麓自盡，武田氏滅亡。',
  roles: { 1575: '包圍長篠城，在設樂原與織田、德川聯軍決戰，損失大批重臣。' },
  routes: { 1575: ['r0'] },
  myths: [{ text: '勝賴是斷送武田家的無能繼承人', note: '這個形象深受江戶時代軍學書《甲陽軍鑑》影響，近年研究對其施政多有重新評價。' }],
  sources: [koto('武田勝頼', 18663)] },
{ id: 'akechi-mitsuhide', name: '明智光秀', kana: 'あけち みつひで', romaji: 'Akechi Mitsuhide', years: '?–1582',
  clan: '明智氏（傳為美濃土岐氏的支流；早年經歷不明）', mon: MON.akechi,
  portrait: pic('akechi-mitsuhide', 'Akechi Mitsuhide.jpg', '作者不詳', '本德寺（大阪府岸和田市）', '公有領域', '安土桃山時代（推定）', null),
  bio: '先後侍奉足利義昭與織田信長，負責平定丹波，並受封近江坂本城。1582 年六月二日襲擊本能寺，十三日在山崎之戰敗給羽柴秀吉，逃亡途中遇害。生年有 1528 年等多種說法。',
  roles: { 1582: '率軍從丹波轉向京都襲擊本能寺；十一天後在山崎之戰敗北。' },
  routes: { 1582: ['r0', 'z0'] },
  myths: [
    { text: '「敵は本能寺にあり」（敵人就在本能寺）', note: '見於江戶後期賴山陽《日本外史》等後世著作，同時代史料沒有這句話。' },
    { text: '謀反動機已有定論', note: '怨恨說、野心說、四國政策說、幕後黑手說等並存，至今沒有定論。' }
  ],
  sources: [koto('明智光秀', 14506), koto('日本外史', 110097)] },
{ id: 'toyotomi-hideyoshi', name: '豐臣秀吉', alias: ['羽柴秀吉'], kana: 'とよとみ ひでよし', romaji: 'Toyotomi Hideyoshi', years: '1537–1598',
  clan: '出身尾張平民；木下→羽柴→豐臣（1586 年受賜豐臣姓）', mon: MON.toyotomi,
  portrait: pic('toyotomi-hideyoshi', 'Toyotomi hideyoshi.jpg', '狩野光信', '高台寺', '公有領域', '約 1601 年', null),
  bio: '在信長麾下崛起。本能寺之變後回師擊敗光秀，又在賤岳之戰打敗柴田勝家；1585 年任關白，1590 年小田原征伐後完成全國統合。1592、1597 年兩度出兵侵略朝鮮，1598 年在伏見城病逝。生年另有 1536 年一說。',
  roles: {
    1582: '在備中高松城與毛利議和後急行回師，在山崎之戰擊敗光秀。',
    1583: '從美濃大垣急返近江，在賤岳之戰擊敗柴田勝家。',
    1590: '動員各地大名包圍小田原，北條氏投降。',
    1592: '下令出兵侵略朝鮮，自己坐鎮肥前名護屋城，並未渡海。'
  },
  routes: { 1582: ['r1', 'z0'], 1583: ['r1'], 1590: ['r0', 'z0'], 1592: ['r0'] },
  quote: { text: '露と落ち 露と消えにし 我が身かな 浪速のことも 夢のまた夢', zh: '如露而生，如露而逝，此身亦然；浪速（大坂）的種種，不過是夢中之夢', source: '傳為秀吉辭世和歌，有傳世懷紙', status: 'attributed',
    note: '一般視為秀吉的辭世之作，但寫作時間與是否親筆仍有討論。' },
  myths: [
    { text: '在寒冬把信長的草鞋揣在懷裡焐暖', note: '出自江戶時代通俗讀物（如《繪本太閤記》），沒有同時代史料。' },
    MYTH_HOTOTOGISU
  ],
  sources: [koto('豊臣秀吉', 19047), koto('甲子夜話', 45237)] },
{ id: 'shibata-katsuie', name: '柴田勝家', kana: 'しばた かついえ', romaji: 'Shibata Katsuie', years: '?–1583',
  clan: '柴田氏（尾張）', mon: MON.shibata,
  portrait: pic('shibata-katsuie', 'Shibata Katsuie large.jpg', '作者不詳', '收錄於福井市立鄉土歷史博物館圖錄（2006）', '公有領域', '桃山至江戶初期', null),
  bio: '織田家重臣，負責北陸方面，以越前北之庄城為據點。信長死後在清洲會議與秀吉對立，並迎娶信長之妹阿市。1583 年賤岳之戰敗北，退回北之庄城，與阿市一同自盡。',
  roles: { 1583: '從越前南下近江柳瀨與秀吉對峙，戰敗後退回北之庄城自盡。' },
  routes: { 1583: ['r0', 'r2'] },
  myths: [{ text: '「瓶割り柴田」：被圍時打破水甕、背水一戰', note: '見於江戶時代的軍記與逸話，史實可疑。' }],
  sources: [koto('柴田勝家', 74720)] },
{ id: 'maeda-toshiie', name: '前田利家', kana: 'まえだ としいえ', romaji: 'Maeda Toshiie', years: '1538?–1599',
  clan: '前田氏（尾張荒子）', mon: MON.maeda,
  portrait: pic('maeda-toshiie', 'Maeda Toshiie.jpg', '作者不詳', '私人收藏', '公有領域', '江戶時代', null),
  bio: '信長的家臣，隸屬柴田勝家的北陸軍，受封能登。賤岳之戰中途撤兵，戰後歸順秀吉，成為加賀前田家（「加賀百萬石」）的始祖，秀吉晚年名列五大老。生年另有 1537、1539 年等說法。',
  roles: { 1583: '隨柴田方出陣，卻在戰局中撤兵退出，戰後歸順秀吉。' },
  routes: { 1583: ['r0'] },
  sources: [koto('前田利家', 16541)] },
{ id: 'hojo-ujinao', name: '北條氏直', kana: 'ほうじょう うじなお', romaji: 'Hōjō Ujinao', years: '1562–1591',
  clan: '後北條氏（小田原）第五代', mon: MON.hojo,
  portrait: pic('hojo-ujinao', 'Hojo Ujinao.jpg', '作者不詳', '圖像出自大阪城天守閣特別展「秀吉への挑戦」圖錄', '公有領域', '1803 年（江戶後期）', '江戶後期繪製，非生前寫生'),
  bio: '後北條氏第五代當主，妻子是家康之女督姬。1590 年被秀吉大軍包圍小田原三個多月後開城投降；父親氏政被命切腹，氏直因是家康女婿而免死，流放高野山，翌年病逝。',
  roles: { 1590: '固守小田原城，約三個月後開城投降，被流放高野山。' },
  routes: { 1590: ['z0'] },
  myths: [{ text: '「小田原評定」：城內只會開會、議而不決', note: '後來成為成語；城內實際議論情形多出自後世記述。' }],
  sources: [koto('北条氏直', 14948), { t: '小田原城｜北條五代', u: 'https://odawaracastle.com/history/hojo-godai/' }] },
{ id: 'yi-sun-sin', foreign: true, name: '李舜臣', kana: '이순신', kanaLabel: '韓文', romaji: 'I Sun-sin（舊拼法 Yi Sun-sin）', years: '1545–1598',
  clan: '德水李氏；朝鮮王朝武將', mon: null, monNote: '朝鮮沒有日本式的家紋傳統，因此不顯示紋章。',
  portrait: null, portraitNote: '沒有生前畫像傳世；現行標準肖像是 20 世紀的現代作品，仍受著作權保護，因此不使用。',
  bio: '朝鮮王朝武將。壬辰戰爭（日本稱文祿之役）時任全羅左道水軍節度使，在玉浦、閑山島等海戰屢次擊敗日本水軍，切斷日軍的海上補給。1597 年鳴梁海戰以寡擊眾，1598 年在露梁海戰中彈陣亡。',
  roles: { 1592: '率全羅左水營水軍出擊，在玉浦（五月）、閑山島（七月）等海戰獲勝，與各地義兵共同抵抗侵略。' },
  routes: { 1592: ['z1'] },
  quote: { text: '必死則生，必生則死', zh: '抱必死決心者得生，貪生者反而會死', source: '李舜臣《亂中日記》丁酉年（1597）九月十五日，鳴梁海戰前一日對將士的訓示', status: 'attested',
    note: '此語化用《吳子》的「必死則生，幸生則死」。另一句「戰方急，慎勿言我死」出自其姪李芬的《行錄》，是死後的追述。' },
  sources: [koto('李舜臣', 148722), { t: '韓國民族文化大百科｜壬辰倭亂', u: 'https://encykorea.aks.ac.kr/Article/E0047674' }] },
{ id: 'konishi-yukinaga', name: '小西行長', kana: 'こにし ゆきなが', romaji: 'Konishi Yukinaga', years: '1558?–1600',
  clan: '小西氏（堺商人出身）；天主教教名 Agostinho', mon: null, monNote: '小西氏家紋說法不一，Commons 上沒有可確認的檔案，因此不顯示。',
  portrait: pic('konishi-yukinaga', 'Daimyo Konishi Yukinaga Ukiyo-e.jpg', '歌川芳幾', null, '公有領域', '1867 年', '幕末浮世繪，屬後世想像畫像'),
  bio: '堺商人小西隆佐之子，天主教大名，肥後宇土城主。侵略朝鮮時任第一番隊先鋒，攻陷釜山、漢城、平壤，也主導與明朝的議和交涉。關原之戰屬西軍，戰後與石田三成一同被處斬（因信仰拒絕切腹）。',
  roles: { 1592: '第一番隊先鋒，四月攻陷釜山鎮與東萊城，率先北上進入漢城。' },
  routes: { 1592: ['r0', 'r1', 'z0'] },
  sources: [koto('小西行長', 65676)] },
{ id: 'kato-kiyomasa', name: '加藤清正', kana: 'かとう きよまさ', romaji: 'Katō Kiyomasa', years: '1562–1611',
  clan: '加藤氏（尾張出身，秀吉的親族家臣）', mon: MON.kato,
  portrait: pic('kato-kiyomasa', 'Katō Kiyomasa.jpg', '作者不詳', '勸持院（京都）', '公有領域', '江戶時代（推定）', null),
  bio: '賤岳七本槍之一，肥後熊本城主。侵略朝鮮時任第二番隊主將，經咸鏡道北上，俘虜朝鮮兩位王子，所到之處也帶給當地民眾重大苦難。關原之戰屬東軍。',
  roles: { 1592: '第二番隊主將，與小西爭先進向漢城，之後轉戰咸鏡道。' },
  routes: { 1592: ['r0', 'r1'] },
  myths: [{ text: '「虎退治」：清正在朝鮮持槍刺殺猛虎', note: '日軍在朝鮮獵虎確有記錄，但清正親手刺虎的英雄形象主要來自後世的讀物與浮世繪。' }],
  sources: [koto('加藤清正', 15704)] },
{ id: 'ishida-mitsunari', name: '石田三成', kana: 'いしだ みつなり', romaji: 'Ishida Mitsunari', years: '1560–1600',
  clan: '石田氏（近江）', mon: MON.ishida,
  portrait: pic('ishida-mitsunari', 'Ishida Mitsunari.jpg', '作者不詳', '宇治主水藏（摹本）', '公有領域', '17 世紀', '絹本著色石田三成像（摹本）'),
  bio: '秀吉親信的奉行，負責太閤檢地與後勤補給。秀吉死後與家康對立，1600 年聯合諸大名組成西軍；關原戰敗後被捕，在京都六條河原處斬。',
  roles: { 1600: '西軍實際上的組織者，從大垣城移往關原，在笹尾山布陣，戰敗後被捕處斬。' },
  routes: { 1600: ['r2'] },
  myths: [{ text: '「三獻茶」：少年三成以溫度不同的三碗茶打動秀吉', note: '首見於江戶時代的逸話集，史實無法證實。' }],
  sources: [koto('石田三成', 15258)] },
{ id: 'mori-terumoto', name: '毛利輝元', kana: 'もうり てるもと', romaji: 'Mōri Terumoto', years: '1553–1625',
  clan: '毛利氏（安藝）', mon: MON.mori,
  portrait: pic('mori-terumoto', 'Mori Terumoto.jpg', '作者不詳', '毛利博物館', '公有領域', '江戶初期', null),
  bio: '毛利元就之孫，統治中國地方的大名，秀吉晚年的五大老之一。1600 年被推為西軍總大將，坐鎮大坂城而未親赴關原；戰後領地削減為周防、長門兩國。',
  roles: { 1600: '名義上的西軍總大將，留守大坂城，未出現在關原戰場。' },
  routes: {}, routeNote: '他留在大坂城，本幕沒有他的行軍路線。',
  sources: [koto('毛利輝元', 16898)] },
{ id: 'kobayakawa-hideaki', name: '小早川秀秋', kana: 'こばやかわ ひであき', romaji: 'Kobayakawa Hideaki', years: '1582–1602',
  clan: '木下家出身（寧寧之兄木下家定之子），入繼小早川氏', mon: MON.kobayakawa, monNote: '左三つ巴為小早川家的家紋；秀秋本人也使用「違い鎌」。',
  portrait: pic('kobayakawa-hideaki', 'Kobayakawa Hideaki 2.jpg', '作者不詳', '東京大學史料編纂所', '公有領域', '17 世紀初', null),
  bio: '秀吉正室寧寧的姪子，曾為秀吉養子，後入繼小早川家。關原之戰中從松尾山倒戈，攻擊西軍的大谷吉繼隊，促成西軍崩潰。戰後受封岡山，兩年後去世，因無子嗣而絕家。',
  roles: { 1600: '在松尾山布陣，開戰後倒向東軍，成為勝負關鍵。' },
  routes: {}, routeNote: '本幕地圖未單獨畫出小早川隊的移動。',
  myths: [{ text: '「問鐵砲」：家康向松尾山開槍，逼猶豫的秀秋表態', note: '首見於後世編纂的史料；近年研究多認為秀秋在開戰後不久就倒戈。' }],
  sources: [koto('小早川秀秋', 16259)] },
{ id: 'toyotomi-hideyori', name: '豐臣秀賴', kana: 'とよとみ ひでより', romaji: 'Toyotomi Hideyori', years: '1593–1615',
  clan: '豐臣氏（秀吉與淀殿之子）', mon: MON.toyotomi,
  portrait: pic('toyotomi-hideyori', 'Hideyori Toyotomi.jpg', '作者不詳', '養源院（京都）', '公有領域', null, null),
  bio: '秀吉與淀殿（茶茶）之子，秀吉死時年僅六歲。家康開設幕府後仍居大坂城，娶家康孫女千姬。1614–1615 年大坂之陣中城破，與母親淀殿自盡，豐臣氏滅亡。',
  roles: {
    1603: '仍居大坂城，豐臣家保有聲望，但政治重心已移往江戶。',
    1615: '大坂夏之陣城破，與母親淀殿在城內自盡。'
  },
  routes: { 1603: [], 1615: ['z0'] }, routeNote: '他居於大坂城，本幕沒有他的行軍路線。',
  sources: [koto('豊臣秀頼', 19048), { t: '大阪城天守閣｜大坂之陣資料', u: 'https://www.osakacastle.net/pdf/leaflet/yukari-osakanojin_202203.pdf' }] },
{ id: 'tokugawa-hidetada', name: '德川秀忠', kana: 'とくがわ ひでただ', romaji: 'Tokugawa Hidetada', years: '1579–1632',
  clan: '德川氏（家康三子）', mon: MON.tokugawa,
  portrait: pic('tokugawa-hidetada', 'Hidetada2.jpg', '作者不詳', '收藏處未標示', '公有領域', null, 'Commons 未標示原件收藏處'),
  bio: '家康的三子，1605 年起任江戶幕府第二代將軍。關原之戰時率主力走中山道，因進攻上田城受阻而遲到；大坂之陣指揮攻城，之後推行武家諸法度等制度，鞏固幕府體制。',
  roles: { 1615: '以將軍身分率軍從江戶西上，與家康一同指揮攻城。' },
  routes: { 1615: ['r1', 'r2'] },
  sources: [koto('徳川秀忠', 19099)] },
{ id: 'sanada-nobushige', name: '真田信繁', alias: ['真田幸村'], kana: 'さなだ のぶしげ', romaji: 'Sanada Nobushige', years: '1567–1615',
  clan: '真田氏（信濃上田）；俗稱「幸村」', mon: MON.sanada,
  portrait: pic('sanada-nobushige', 'Sanada Yukimura.jpg', '作者不詳', '上田市立博物館', '公有領域', '江戶時代', null),
  bio: '真田昌幸的次子。關原之戰時與父親守上田城，牽制德川秀忠，戰後被流放到紀伊九度山。大坂之陣入城，冬之陣築出城「真田丸」，夏之陣突擊家康本陣，在今天王寺附近戰死。',
  roles: { 1615: '大坂夏之陣突擊家康本陣，一度逼得本陣動搖，最後戰死。' },
  routes: { 1615: ['z0'] },
  quote: { text: '真田日本一の兵', zh: '真田是日本第一的勇士', source: '島津家久書信（收於《薩藩舊記雜錄》），轉述大坂之陣的戰況', status: 'attested',
    note: '這是敵方陣營對他的評語，不是信繁本人的話。' },
  myths: [
    { text: '「真田幸村」這個名字', note: '同時代史料都稱他為「信繁」；「幸村」出自江戶時代的軍記物。' },
    { text: '真田十勇士', note: '是後世講談與小說的創作。' }
  ],
  sources: [koto('真田信繁', 1324987)] }
];

const byId = {}, byName = {};
for (const f of F) { byId[f.id] = f; byName[f.name] = f.id; (f.alias || []).forEach(a => { byName[a] = f.id; }); }
window.sengokuFigures = { list: F, byId, byName, find: name => byId[byName[name]] || null };
})();
